In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
hourly_data = pd.read_csv('https://raw.githubusercontent.com/PacktWorkshops/The-Data-Analysis-Workshop/master/Chapter01/data/hour.csv')

In [3]:
# Print some generic statistics about the data
print(f'Shape of data: {hourly_data.shape}')
print(f'Number of missing values in the data: {hourly_data.isnull().sum().sum()}')

Shape of data: (17379, 17)
Number of missing values in the data: 0

In [4]:
# Get statistics on the numerical columns
hourly_data.describe()

,instant,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
count,17379.0000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000
mean,8690.0000,2.501640,0.502561,6.537775,11.546752,0.028770,3.003683,0.682721,1.425283,0.496987,0.475775,0.627229,0.190098,35.676218,153.786869,189.463088
std,5017.0295,1.106918,0.500008,3.438776,6.914405,0.167165,2.005771,0.465431,0.639357,0.192556,0.171850,0.192930,0.122340,49.305030,151.357286,181.387599
min,1.0000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.020000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,4345.5000,2.000000,0.000000,4.000000,6.000000,0.000000,1.000000,0.000000,1.000000,0.340000,0.333300,0.480000,0.104500,4.000000,34.000000,40.000000
50%,8690.0000,3.000000,1.000000,7.000000,12.000000,0.000000,3.000000,1.000000,1.000000,0.500000,0.484800,0.630000,0.194000,17.000000,115.000000,142.000000
75%,13034.5000,3.000000,1.000000,10.000000,18.000000,0.000000,5.000000,1.000000,2.000000,0.660000,0.621200,0.780000,0.253700,48.000000,220.000000,281.000000
max,17379.0000,4.000000,1.000000,12.000000,23.000000,1.000000,6.000000,1.000000,4.000000,1.000000,1.000000,1.000000,0.850700,367.000000,886.000000,977.000000

In [5]:
hourly_data.T

,0,1,2,3,4,5,6,7,8,9,...,17369,17370,17371,17372,17373,17374,17375,17376,17377,17378
instant,1,2,3,4,5,6,7,8,9,10,...,17370,17371,17372,17373,17374,17375,17376,17377,17378,17379
dteday,2011-01-01,2011-01-01,2011-01-01,2011-01-01,2011-01-01,2011-01-01,2011-01-01,2011-01-01,2011-01-01,2011-01-01,...,2012-12-31,2012-12-31,2012-12-31,2012-12-31,2012-12-31,2012-12-31,2012-12-31,2012-12-31,2012-12-31,2012-12-31
season,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
yr,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
mnth,1,1,1,1,1,1,1,1,1,1,...,12,12,12,12,12,12,12,12,12,12
hr,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
holiday,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
weekday,6,6,6,6,6,6,6,6,6,6,...,1,1,1,1,1,1,1,1,1,1
workingday,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
weathersit,1,1,1,1,1,2,1,1,1,1,...,2,2,2,2,2,2,2,1,1,1
temp,0.24,0.22,0.22,0.24,0.24,0.24,0.22,0.2,0.24,0.32,...,0.28,0.28,0.26,0.26,0.26,0.26,0.26,0.26,0.26,0.26
atemp,0.2879,0.2727,0.2727,0.2879,0.2879,0.2576,0.2727,0.2576,0.2879,0.3485,...,0.2727,0.2879,0.2576,0.2879,0.2727,0.2576,0.2576,0.2576,0.2727,0.2727
hum,0.81,0.8,0.8,0.75,0.75,0.75,0.8,0.86,0.75,0.76,...,0.45,0.45,0.48,0.48,0.48,0.6,0.6,0.6,0.56,0.65
windspeed,0,0,0,0,0,0.0896,0,0,0,0,...,0.2239,0.1343,0.194,0.0896,0.1343,0.1642,0.1642,0.1642,0.1343,0.1343
casual,3,8,5,3,0,0,2,1,1,8,...,62,69,30,14,10,11,8,7,13,12
registered,13,32,27,10,1,1,0,2,7,6,...,185,246,184,150,112,108,81,83,48,37
cnt,16,40,32,13,1,1,2,3,8,14,...,247,315,214,164,122,119,89,90,61,49